merge:
	whitelist:
		# a PR must have these labels set
		labels: ["automerge"]
	blacklist:
		# a PR may not have these labels set
		labels: ["wip"]
	# merge method, see https://help.github.com/en/articles/about-merge-methods-on-github
	# one of: merge, squash, rebase
	method: squash
	# statuses required in addition to the ones defined in GitHub
	# required_statuses:
	# 	- "test1"
	# 	- "test2"
	delete_after_merge: true
