AllCops:
  Exclude:
    - vendor/**/*
  TargetRubyVersion: 2.5

Gemspec/RequiredRubyVersion:
  Enabled: false

# Remove this
Metrics/AbcSize:
  Max: 74

Metrics/BlockLength:
  Exclude:
    - test/**/*_test.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*_test.rb

# Remove this
Metrics/CyclomaticComplexity:
  Max: 17

# Remove this
Metrics/MethodLength:
  Max: 47

# Remove this
Metrics/ModuleLength:
  Max: 500

# Remove this
Metrics/PerceivedComplexity:
  Max: 18

Style/Documentation:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false
