AllCops:
  Exclude:
    - vendor/**/*
  TargetRubyVersion: 2.5

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - test/**/*_test.rb

Metrics/BlockLength:
  Exclude:
    - test/**/*_test.rb

Style/Documentation:
  Enabled: false
