AllCops:
  Exclude:
    - vendor/**/*
  TargetRubyVersion: 2.5

Gemspec/RequiredRubyVersion:
  Enabled: false

# Remove this
Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - test/**/*_test.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*_test.rb

# Remove this
Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false
