name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
        - 2.7
        - 3.0
        - 3.1

    name: Ruby ${{ matrix.ruby }}
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsqlite3-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Run RuboCop
      run: bundle exec rubocop
    - name: Run RSpec specs
      run: bundle exec rspec
